### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by stepanenko3** [optimistdigital/nova-multiselect-field#136]

**Comment by Tarpsvo** [comment]
Seems to work fine with Laravel 9. Can you elaborate what's stopping you? Thanks!

**Comment by aliwesome** [comment]
@Tarpsvo I have found the issue that we can not upgrade our projects to Laravel 9.

The reason is because of dependency to lower version of `outl1ne/nova-translations-loader` package which is `^3.0.0` and in this version there is no support for Laravel 9, so an upgrade to `3.1.4` will fix this issue. 

I will send a PR for this.
