### ISSUE TITLE
Get options by ajax

### ISSUE THREAD

**Issue by bigperson** [optimistdigital/nova-multiselect-field#21]
Is it possible like options by ajax request?

**Comment by nizam27391** [comment]
Hi.

Same request like above. How do we get by ajax. Want to implement filters on search as currently my tagging field is super big.

Thanks

**Comment by Tarpsvo** [comment]
There's currently no way to do this. If you have any ideas how to create support for this, pull requests are welcome!

**Comment by vesper8** [comment]
This is not difficult to do.. I use vue-multiselect extensively and exclusively with ajax requests and it's not hard to implement at all.. @Tarpsvo as you are already very familiar with your project then perhaps you can add this functionality after I explain how I do it. Basically you would only require the user to pass an api endpoint and then you'd have an ajax autocomplete search working very easily.

I do feel this is a must-have feature for any autocomplete and is the reason why I came to your package just now

The key is to add this to the `<multiselect />`

```
@search-change="asyncFindApi"
```

And then this is the `asyncFindApi` method

```
    async asyncFindApi(query) {
      if (query.length >= this.minimumSearchQuery) {
        this.results = [];
        try {
          await this.$http
            .get(this.api, {
              params: {
                query,
              },
            })
            .then((response) => {
              this.results = response.data;
              this.isLoading = false;
            })
            .catch((err) => {
              console.log('err', err);
            });
        } catch (error) {
          // console.log('error performing search!');
        }
      }
    },
```

Optionally I'm using a `minimumSearchQuery` so that it only starts to search after you've entered at least 3 characters. Then it's up to the user to create an api endpoint that receives a query and returns the results that match in json format

For clarity, this is my `autocomplete-search.vue` component that is built for re-usability

```
<template>
  <div class="input-group">
    <multiselect
      v-model="selected"
      label="name"
      track-by="name"
      :placeholder="options.placeholder"
      open-direction="bottom"
      :options="results"
      :searchable="true"
      :show-labels="false"
      :loading="isLoading"
      :options-limit="optionsLimit"
      :internal-search="false"
      :max-height="600"
      :custom-label="customLabel"
      selected-label=""
      select-label=""
      deselect-label="X"
      data-lpignore="true"
      @search-change="asyncFindApi"
      @select="onSelect"
      @open="openSearch"
    >
      <template slot="noResult">
        {{ options.noResult }}
      </template>
      <span
        slot="caret"
        class="icon-search"
      >
        <i
          class="fas fa-search"
          aria-hidden="true"
        />
      </span>
    </multiselect>
  </div>
</template>

<script>
import multiselect from 'vue-multiselect';

export default {

  components: {
    multiselect,
  },

  props: {
    api: {
      type: String,
      default: () => null,
    },
    options: {
      type: Object,
      default: () => ({
        placeholder: 'Search',
      }),
    },
    customLabel: {
      type: Function,
      default: (option) => `${option.id}`,
    },
  },

  data() {
    return {
      selected: null,
      results: [],
      isLoading: false,
    };
  },

  computed: {
    optionsLimit() {
      return 10;
    },

    minimumSearchQuery() {
      return 3;
    },
  },

  methods: {
    onSelect(option) {
      // console.log('onselect.option', option);
      this.$emit('onSelect', option);
    },

    openSearch() {
      this.results = [];

      $('.multiselect input[type=text]').each((index, element) => {
        $(element).attr('data-lpignore', true); // prevent lastpass autocomplete
      });
    },

    async asyncFindApi(query) {
      if (query.length >= this.minimumSearchQuery) {
        // console.log(query);
        this.results = [];
        try {
          this.isLoading = true;

          await this.$http
            .get(this.api, {
              params: {
                query,
              },
            })
            .then((response) => {
              this.results = response.data;
              this.isLoading = false;
            })
            .catch((err) => {
              console.log('err', err);
            });
        } catch (error) {
          // console.log('error performing search!');
        }
      }
    },
  },
};
</script>
```

And this is an example of how I include it

```
      <autocomplete-search
        api="/api/cities/search"
        :options="{
          placeholder: 'Enter a location',
          noResult: 'No cities matching'
        }"
        :custom-label="(option) => `${option.location}`"
        @onSelect="setLocation"
      />
```

**Comment by vesper8** [comment]
@Tarpsvo any thoughts on my comment above and adding this feature to your multiselect field? I feel like it would make it so much more useful and there doesn't seem to be any other custom select fields that support this right now.

It would also help address this issue here https://github.com/laravel/nova-issues/issues/2345

Do you have any questions about my implementation above?

Thanks

**Comment by Tarpsvo** [comment]
Hi @vesper8!

Awfully sorry for the long delay with the response. I've been incredibly busy with work and haven't had time to work on new features, I'm currently just fixing bugs as they come up.

Your implementation does seem good and solid, when I finally get back to adding more features, this will definitely be at the top of my list. Until then, I'll keep this issue open.

Thanks!
